version: '3'
services:
  db:
    image: mysql:5.7
    container_name: test_db
    volumes:
      - my-db:/var/lib/mysql
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '12345678'
      MYSQL_DATABASE: 'liquibase-springboot'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: '12345678'

volumes:
  my-db: