version: '3'
services:
  db1:
    image: mysql:8.0
    container_name: test_db1
    volumes:
      - my-db1:/var/lib/mysql
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '12345678'
      MYSQL_DATABASE: 'hb-product'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: '12345678'

  db2:
    image: mysql:8.0
    container_name: test_db2
    volumes:
      - my-db2:/var/lib/mysql
    restart: always
    ports:
      - '3307:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '12345678'
      MYSQL_DATABASE: 'second-db'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: '12345678'

volumes:
  my-db1:

  my-db2: