version: '3'
services:
  db1:
    image: mysql:8.0
    container_name: test_db1
    volumes:
      - my-db1:/var/lib/mysql
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '12345678'
      MYSQL_DATABASE: 'hb-product'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: '12345678'

  db2:
    image: mysql:8.0
    container_name: test_db2
    volumes:
      - my-db2:/var/lib/mysql
    restart: always
    ports:
      - '3307:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '12345678'
      MYSQL_DATABASE: 'second-db'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: '12345678'

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    ports:
      - "3308:3306"
    #command: --init-file /data/application/init.sql
    volumes:
      - mysql_data:/var/lib/mysql
      # - ./init.sql:/data/application/init.sql
    environment:
      - MYSQL_DATABASE=keycloak
      - MYSQL_USER=keycloak
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=123456
    healthcheck:
      test: "mysqladmin ping -u root -p$${MYSQL_ROOT_PASSWORD}"

  keycloak:
    image: quay.io/keycloak/keycloak:20.0.1
    container_name: keycloak
    restart: always
    volumes:
      - ./keycloak:/opt/jboss/keycloak/imports
    environment:
      - DB=mysql
      - DB_URL_HOST=mysql
      - DB_URL_DATABASE=keycloak
      - DB_USERNAME=keycloak
      - DB_PASSWORD=password
      - DB_SCHEMA=keycloak
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - "8080:8080"
    command:
      - "-Dkeycloak.import=/opt/jboss/keycloak/imports/ProductManagement-realm.json"
      - "start-dev --http-port 8080"
    depends_on:
      - mysql
    healthcheck:
      test: "curl -f http://localhost:8080/admin || exit 1"

volumes:
  my-db1:
  my-db2:
  mysql_data:
    driver: local